#!/bin/bash

# Get hostname
hostname=$(hostname)

# Pperating system information
os_info=$(lsb_release -d | cut -f2)

#System uptime
uptime_info=$(uptime -p)

# Linux kernel version
kernel_version=$(uname -r)

# CPU information
cpu_info=$(lscpu | grep 'Model name' | awk -F: '{print $2}' | xargs)

# Memory information in human-readable format
memory_info=$(free -h | grep Mem | awk '{print "Total: "$2", Used: "$3", Free: "$4}')

# IP and MAC address information for all network interfaces
ip_info=$(ip -o -4 addr show | awk '{print $2, $4}')
mac_info=$(ip link show | awk '/ether/ {print $2}')

# Filesystem utilization in human-readable format and filesystem types
filesystem_info=$(df -hT | awk '{print $1, $2, $3, $4, $5, $6}')

# Get the last five lines of the general log file containing the word "error" (case-insensitive)
log_errors=$(grep -i "error" /var/log/syslog | tail -n 5)

# Output the collected information
echo "System Hostname: $hostname"
echo "Operating System: $os_info"
echo "System Uptime: $uptime_info"
echo "Linux Kernel Version: $kernel_version"
echo "CPU Information: $cpu_info"
echo "Memory Information: $memory_info"
echo "IP Information: $ip_info"
echo "MAC Information: $mac_info"
echo "Filesystem Utilization and Types:"
echo "$filesystem_info"
echo "Last 5 log errors:"
echo "$log_errors"

#Save Sh
chmod +x tasks.sh
